spring:
  application:
    name: desafiopagamento

  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect